language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t cgovande/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cgovande/react-test npm test

after_success:
  - docker build -t cgovande/multi-client ./client
  - docker build -t cgovande/multi-nginx ./nginx
  - docker build -t cgovande/multi-server ./server
  - docker build -t cgovande/multi-worker ./worker
  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cgovande/multi-client
  - docker push cgovande/multi-nginx
  - docker push cgovande/multi-server
  - docker push cgovande/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-262305441776"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
